### ISSUE TITLE
Make HTML Field default

### ISSUE THREAD

**Issue by hericks** [ijgnd/anki__editor_edit_html_extended#2]
Hey, 

I really love your add-on and wanted to ask if there is any way to default some fields to the HTML-Editor (CMD+Shift+X). This would remove the unnecessary opening/closing of the "Edit HTML"-window, when adding a new card. 

Thank you for your support!

**Comment by ijgnd** [comment]
I don't understand. Could you reword/extend your post? 

Maybe interesting/relevant: [Show field's source (html) in editor](https://ankiweb.net/shared/info/1574324795)

**Comment by hericks** [comment]
This add-on does show the HTML source in the editor by default, but it does not allow to paste the HTML as in the CMD-Shift-X field.

I'd like that the default field is just the field I can open with CMD-Shift-X. At the moment my workflow works like this:

1. Write HTML in external editor
2. Copy HTML source from external editor
3. Click on field in 'Add new note' dialog
4. Press CMD-Shift-X to open 'Edit HTML' dialog
5. Paste the HTML source
6. Close the 'Edit HTML' dialog
7. Repeat for every field of the new note

I'd like to skip 4. and 6. This would be possible if the default text-field were the HTML-field. This is true for the listed plugin, but pasting doesn't work correctly (newlines are replaced by `<br>`, I already posted an Issue there).

**Comment by ijgnd** [comment]
I think I understand what you want but I still don't understand how my add-on would help you.

> This is true for the listed plugin, but pasting doesn't work correctly (newlines are replaced by <br>

For me this is only true in the editor view. If I later toggle to the regular view and then use Ctrl+Shift+x to I see that the linebreaks are in the source. So for future editing it should still be good. I have no idea how to adjust arthur's add-on.

My add-on "anki__editor_edit_html_extended" does not care about line breaks in the source - in fact it removes them after from a field edited in my add-on. 

maybe also interesting: [External Editor](https://ankiweb.net/shared/info/16727059).
