### ISSUE TITLE
Font not monospaced on macOS

### ISSUE THREAD

**Issue by NSBum** [ijgnd/anki__editor_edit_html_extended#5]
On macOS, the editor window displays only in proportional fonts; for code-editing monospaced fonts would be preferable. However, I couldn't sort out where in the theme css to make the change. Is there a global css pref for font face?

[Later] -I did notice that by directly editing the codemirror css files that I can change the font, i.e. 

```
.CodeMirror * {
  font-family: Menlo, monospace;
  font-size: 13px;
}
```

but wondering whether font selection could be implemented upstream of that...

<img width="807" alt="Screen Shot 2020-12-18 at 9 32 31 AM" src="https://user-images.githubusercontent.com/10759859/102625807-0725c800-4114-11eb-92c9-0573a84ffc1e.png">

**Comment by ijgnd** [comment]
thanks for this report. I just uploaded a new version to ankiweb with new user settings. Could you update your add-ons (which will overwrite your fix), restart, adjust your config, and try again. Let me know if it works or if you still have a problem/bug.

**Comment by NSBum** [comment]
That's brilliant. Works beautifully.  Having poked around I found the fix and was just about to do a formal pull request but you beat me to it!

@NSBum a.k.a u/ojisanseiuchi
