### ISSUE TITLE
The newest v.2022-09-10 breaks editor_menu_show_button

### ISSUE THREAD

**Issue by kvn1351** [ijgnd/anki__editor_edit_html_extended#7]
As the title implies, `editor_menu_show_button` is broken after today's update. I've set it to false but it shows up anyways.

**Comment by ijgnd** [comment]
With yesterday's update I also changed some names in the config to make them more clear, e.g. I changed ` editor_menu_show_button` to `anki editor: add button` ([commit](https://github.com/ijgnd/anki__editor_edit_html_extended/commit/1f043730e120e3b5a0e1db09503eff50bded0e8a)) to make clear that this "editor" related setting does not refer to an external text editor.

To get the new config keys and remove the now useless old ones I would reset the config. Somewhere at the bottom of the config window for an add-on there's a button "Reset Defaults".

I did not expect that anyone would change these settings so I didn't mention it.

If the problem persists and/or you find other problems please let me know.

**Comment by kvn1351** [comment]
Thanks :)
